# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    image.storage_dir: '%kernel.project_dir%/%env(IMAGE_STORAGE_DIR)%'
    archive.storage_dir: '%kernel.project_dir%/%env(ARCHIVE_STORAGE_DIR)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Core\Shared\Application\Port\AsyncCommandBus:
        class: App\Infrastructure\Bus\MessengerAsyncCommandBus
        arguments:
            $bus: '@messenger.default_bus'

    App\Core\Image\Application\Port\ImageStorage:
        class: App\Infrastructure\Storage\LocalImageStorage
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Core\Image\Application\Port\TempImageStorage:
        class: App\Infrastructure\Image\Storage\LocalTempImageStorage
        arguments:
            $tmpUploadDir: '%kernel.project_dir%/%env(TMP_UPLOAD_DIR)%'

    App\Core\Image\Application\Port\ImageProcessor:
        class: App\Infrastructure\Image\Processing\GdImageProcessor

    App\Core\Shared\Application\Port\Logger:
        class: App\Infrastructure\Logging\MonologAdapter
        arguments:
            $monolog: '@logger'

    Predis\Client:
        arguments:
            - '%env(MESSENGER_TRANSPORT_DSN)%'

    App\Core\Image\Application\Port\ImageProcessingTracker:
        class: App\Infrastructure\Image\Processing\RedisImageProcessingTracker
        arguments:
            $redis: '@Predis\Client'
            $ttlSeconds: '%env(int:REDIS_TTL_SECONDS)%'

    App\Core\Image\Application\Handler\ProcessImageHandler:
        arguments:
            $storageDir: '%image.storage_dir%'
            $archiveDir: '%archive.storage_dir%'

    App\Core\Image\Application\Port\ArchiveStorage:
        class: App\Infrastructure\Storage\LocalArchiveStorage
        arguments:
            $archiveDir: '%archive.storage_dir%'
